(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJgALTMVIgBANQgBAOALAAIAxAAQAMAAABALIAACUQAAAHAEADQAFABAJAAQAKAAAEgBQAFgDAAgHIAAiUQgBgLAMAAIAyAAQALABAAgTQAAgRgMAAIifAAQgIAAgBAIgADSOMIBBBGQAHAJATgBQAOAAAEgEQAGgFgIgJIhOhVQgJgKAJgIIBAg7QAKgJgMgLQgMgMgNALIhKBDQgFAFgEABQgFADgLgBQgJABAAgNIAAg3QAAgMgSgBQgKAAgEACQgGADAAAIIAAC1QABAMAQAAQAVABAAgMIAAg8QAAgGAEgFQADgFAFAAQATABALAIgAhwOXQALAAAGAJIAfAxQAHAKARgBQAOAAAEgEQAFgEgFgIIgjgxQgDgGAHgHQAPgKAIgJQAPgQAAgXQAAgggVgTQgUgTggAAIhrAAQgKABABAHIAAC7QAAALAMAAIAPAAQAKgCAAgGIAAgxQgBgEAEgDQAEgDADAAgAmQOxQAHAAADAGIAOAbQADAJAPgBQAHAAAHgBQAJgEgDgGIhYi7QgEgJgMAAQgKAAgFAKIhZC5QgGAMAXAAQASAAACgIIAMgWQAFgLAJAAgArGNkIANBsQABAFAFADQAFADAFgBQAXAAgBgKIgVi2QgCgIgEgDQgDgCgGgBQgLABgEAHIg8BRQgHAIgDAAQgFgBgFgHIg5hPQgEgJgKAAQgLAAgEAFQgEADgBAJIgVCyQAAAFAGADQAFADAFgBQAUAAABgKIAPhqQAAgGAGgBQAEABACADIAtA8QAEAGAHAAQAGAAAEgFIAwg/QADgDAEgBQAFABACAGgAGyMbIAACvQAAAPAMAAICdAAQAKgBAAgQQAAgTgKAAIh6AAQgKAAAAgKIAAgfQAAgKALAAIBGAAQALAAgBgSQAAgSgKAAIhHAAQgKAAAAgJIAAgcQABgIAIgBIB6AAQAHABADgGQACgEAAgJQAAgJgCgDQgDgFgGAAIidAAQgMAAAAAOgAT4IxQgMAMAAATQAAASAMANQAOANARAAQATAAANgNQANgNAAgSQAAgTgNgMQgNgOgTAAQgRAAgOAOgAP5JKQAlAMA0AAQBUAAAzgsQAzgtgBhKQAAgggMgfQgMgegWgXQgUgVgXgSQgWgRgzgjIgqgeQgbgWgMgSQgJgLAAgXQAAgaARgPQASgQAdAAQAtAAAjAbQAOALAGAHQAHAHAOAVQAKAPAMAAQAKgBAIgFQAHgGAAgJQgBgIgBgEIgUhbQgGgZgSAAQgFABgDABIgKAGQgLAHgIAAIgMgBIgVgGQgkgIgmAAQhGAAgrAmQgrAmAAA9QAAA0AgAlQATAXASAOIBOA4QA/ArAbAdQAbAfABAhQgBAigZAVQgaAUgqAAQgkAAghgSQgigRgWgfIgMgRQgJgMgMAAQgMAAgHAHQgIAJAAALQAAAJACAIIAVBVQAFAPAFAGQAGAHALAAQAJAAALgIQAJgJAJAAIASAFgAjRF+QAHAAACALIABACQAYBeBGA2QBGA2BlABQCCgBBMhQQBMhRAAiIQAAiFhMhQQhMhQiAAAQhmAAhHA3QhGA2gYBfIgBABQgBAKgIABQgHABgCgMQgWhfhHg3QhIg3hpAAQh/AAhMBQQhLBRgBCIQAACFBNBRQBLBQB+AAQBogBBIg2QBGg2AYhfIABgCQACgKAGAAIABAAgAFmIeQgFAHAAAKQAAANAKAFQAGADAVADQBdANBrABQBGgBAwgOQAxgNAlgeQAugmAag9QAZg+AAhNQAAhFgUg4QgUg4glglQgngog0gSQg2gShPAAQhrAAhdANQgVADgGADQgKAGAAAMQAAALAFAGQAHAIAIgBIARAAQAKABAFAKQACALABAXIAAF5QgBAYgCAKQgFALgKAAIgRAAQgIAAgHAHgAyyIgQgGAGgBALQAAAOAJAFQAIAFAXAAICcAAQAXAAAKgFQAIgFABgOQgBgLgFgGQgHgIgKAAIgTAAQgMABgGgLQgCgHAAgbIAAiKQAAgZAIgGQAEgDAeAAIBGAAQAbAAAHADQAIAEACAMIAAAGQAEAWATAAQAOAAAFgJQAFgIAAgWIAAhIQAAgWgFgJQgFgJgOAAQgTAAgEAWIAAAEQgCANgIADQgHAEgbAAIhGAAQgdAAgFgDQgIgGAAgZIAAhkQgBgjAJgIQAIgJAjAAIBtAAQAgAAAMAEQAQAFAFAQQAFANAEAFQAHANAOAAQANAAAFgIQAEgJgDgRIgMg6QgFgWgaABIlvAAQgWgBgJAGQgIAFgBAOQABAKAGAHQAHAHAJAAIARAAQAEAAAEADQAEAEABAFQAEALAAAXIAAF7QAAAYgDAKQgEALgKgBIgRAAQgJAAgHAIgACnrWQADAJgKADQgoAOgmATQgmATgYATQg6AngfBDQghBDAABZQAACLBPBUQBOBUCEAAQCHAABQhUQBQhVgBiOQABikhphOQg7gsg3AGQgiAEgFATQgEAUAaAKQA2AUAZA7QAXA4AABfQAABwgqBCQgrBChJAAQhMAAgphAQgrhBAAhxQAAhRAQgyQATg/AvgvQAegdBGgjQA+geAigsQAUgZAAgVQABgTgPgFQgMgDgNAMIgYAXQgvAfg4gTQgugOglgpQgbgfgogIQgcgGggAHQgKADgDgHQgEgHALgIQAcgVAqACQAvABAfAdQAeAbAgAPQAkAQAagEQARgDAAgPQAAgOgSgGQgggMgmg2Qglgzg1gQQhPgWhJA8QhDA4gYBWQgGAXALALQANALAUgJQA6gaAvAXQAJAEAhATQAcASAWAJQAsASA7gLIAGgBQAIAAABAIgAvDlQIBJDYQAHAYALAKQALAJATAAQATAAAKgLQALgMAJgeICHm0QAHgWAHgJQAIgJALgBQAjgFAAAxIAAF9QAAAbgCAHQgBAEgFADQgEADgFAAIgRAAQgIAAgHAHQgGAHAAAKQAAAOAIAFQAIAFAWAAICbAAQAUAAAIgFQAIgFAAgNQABgLgGgHQgGgHgJAAIgQAAQgLAAgGgKQgCgKAAgYIAAiBQABgdAFgHQAGgGAXgBIB0AAQAXABAGAHQADAEABAGIABAeIAAB8QAAAbgDAHQgGAKgJAAIgQAAQgJAAgHAHQgHAHAAAKQABAOAHAFQAJAFAWAAICaAAQAWAAAJgFQAIgFAAgOQAAgKgGgHQgGgHgJAAIgSAAQgFAAgDgDQgFgDgCgEQgCgLAAgXIAAl9QAAgYACgKQACgEAFgEQADgCAFAAIASAAQAIgBAHgGQAGgHAAgLQABgOgKgFQgIgFgWAAIiaAAQgWAAgJAFQgJAFAAAOQAAALAHAHQAGAGALABIAQAAQAKAAAFAKQADAGAAAcIAABoIgBAeQgBAHgDADQgGAIgXAAIh0AAQgXAAgGgHQgFgGgBgeIAAhtQAAgaACgIQAGgKALAAIAQAAQAJgBAGgGQAGgHAAgLQAAgOgIgFQgIgFgVAAIkmAAQgRAAgIAFQgHAHgBAMQABAVAbADQAdADAAASQABAJgEAMIheE6QgBAGgFAAQgEABgCgFIhfkuQgJgZABgKQAAgLAFgGQAGgEARgCQAbgEABgTQAAgXgdAAIinAAQgeAAABAZQAAAKAFAFQAFAFAOAEQAPADAGAFQAHAEADAJIAmBvQAHAXgJAZIg+C2QgCAGgFABQgEAAgCgGIhzlHQgDgKAAgJQgBgKAHgFQAGgFAOgBQARgCAGgEQAIgFAAgLQAAgXgcAAIiwAAQgcAAAAAWQAAAKAFAGQAFAFAOACQAUAEAHAIQAHAHAKAaICmG+QAJAZAKAJQALAJATAAQAQAAANgJQAGgHALgbIBMjYQACgEAFAAQADAAACAEgAOkiCQgGAHAAAKQAAAOAIAFQAJAGAVAAIFigBQAOAAAHgFQAHgFADgLIANhCQAEgQgFgJQgGgJgLAAQgPABgJAQIgHAPQgPAfgvAAIhVAAQgjAAgPgFQgKgEgDgLQgDgLAAgiIAAhrQAAgaAIgFQAEgDAfgBIAnAAQAaABAIADQAHADACANIABAGQAEAWASgBQAOABAFgJQAGgJgBgWIAAhIQABgWgGgIQgFgJgOAAQgTAAgDAVIgBAFQgCANgHADQgHAEgbAAIgnAAQgfAAgEgEQgIgEAAgaIAAhlQAAgiAJgJQAIgJAjAAIBPAAQAgABAMADQAPAGAHAPQAFAQADADQAHANAOgBQAMAAAGgIQAEgJgDgQIgMg7QgEgVgaAAIlTAAQgVAAgJAFQgJAGAAANQAAAKAGAHQAIAIAIgBIARAAQAEABAEADQAEADABAGQAEAIAAAZIAAF8QAAAagEAIQgBAFgDADQgEADgFAAIgRAAQgIAAgHAGgAHziCQgHAHAAAKQAAAOAIAFQAIAFAWAAIE/AAQAaAAAEgVIAOhCQADgQgFgJQgFgJgMAAQgPABgIAQIgIAPQgOAfgwAAIgwAAQgaABgLgCQgLgCgHgEQgHgFgCgJQgCgJAAgdIAAlkQAAgcACgGQADgLAPAAIASAAQAJAAAHgGQAHgHgBgLQAAgNgJgGQgIgFgXAAIidAAQgWAAgJAFQgJAGAAANQABALAGAHQAHAGAKAAIAQAAQALAAADALQADAJAAAZIAAGAQAAAXgDAIQgCAEgEAEQgEADgEAAIgQAAQgKAAgFAGg");
	this.shape.setTransform(0,1,0.17,0.17);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAZQgKgKAAgPQAAgOAKgLQAKgJAOgBQAPABAKAJQAKALAAAOQAAAPgKAKQgKALgPgBQgOABgKgLgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgUIAFAAIAOAUIAKAAg");
	this.shape_1.setTransform(22.1,11,0.17,0.17);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-1.9,15.4,0.17,0.17);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(22.2,10.8,0.17,0.17);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCtQgog+AAhsQAAhuAog/QApg/BFAAQBGAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_4.setTransform(-8.3,6.1,0.17,0.17);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgxQABgEADAAQADAAACAEIAZAyQABADgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-7.5,15.9,0.17,0.17);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(10.9,6.1,0.17,0.17);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_7.setTransform(1.2,6.1,0.17,0.17);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogo, new cjs.Rectangle(-29.7,-28.7,59.4,59.4), null);


(lib.signupmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAfIAAg+IAWAAIALACQAGACAFADQAFAFADAFIACAHIABAHIgBAIIgCAGIgEAFIgEAFQgFADgGACIgLACgAgSAYIALAAQAGAAADgCQAFgBAEgDQADgDADgFIABgFIABgFIgBgFIgBgEQgDgFgDgDQgEgDgFgCQgDgBgGAAIgLAAg");
	this.shape.setTransform(-72.2,11.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAfIAAg+IAnAAIAAAIIgeAAIAAATIAdAAIAAAGIgdAAIAAAWIAgAAIAAAHg");
	this.shape_1.setTransform(-78.4,11.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMAfIgPgcIgKAAIAAAcIgJAAIAAg+IAVAAIAHACQAFAAADACIAFAFQABAEAAAFQAAAHgEAEIgFACIgGACIARAdgAgNgDIAKAAIAFgBIAFgCIAEgCIAAgFIAAgFIgDgDIgFgCIgFAAIgLAAg");
	this.shape_2.setTransform(-83.9,11.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgEAfIAAg+IAIAAIAAA+g");
	this.shape_3.setTransform(-88.3,11.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUAfIAAg+IATAAIAIACIAIADQADACACADQABAEAAAEQAAAFgBADQgDAEgDABIgHACIgIABIgKAAIAAAcgAgLgDIAJAAIAFgBIAFgBIADgDIABgFIgBgFIgDgDIgFgCIgFAAIgJAAg");
	this.shape_4.setTransform(-92.1,11.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLAfQgGgCgDgFIAGgGQADAEADACQAEACAEAAIAEgBIAEgCIADgDIABgFQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBIgDgDIgFgCIgFgCIgGgCIgFgDIgEgFQgBgDAAgEQAAgFACgDQACgEADgCQADgCAEgBIAGgBIAGAAIAFACQAFACADADIgHAGIgFgEQgDgCgEAAIgDABIgEACIgDADIgBAFIABAEIADADIAEACIAEACIAGACIAGACIAFAFQABADAAAFQAAAFgCAEQgBADgDADQgEACgEABIgHABQgGAAgFgCg");
	this.shape_5.setTransform(-97.8,11.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQAfIghgyIAAAyIgJAAIAAg+IAMAAIAgAyIAAAAIAAgyIAJAAIAAA+g");
	this.shape_6.setTransform(-103.9,11.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEAfIAAg+IAIAAIAAA+g");
	this.shape_7.setTransform(-108.7,11.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDAfIAAg2IgVAAIAAgIIAxAAIAAAIIgUAAIAAA2g");
	this.shape_8.setTransform(-115,11.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUAfIAAg+IAnAAIAAAIIgeAAIAAATIAdAAIAAAGIgdAAIAAAWIAgAAIAAAHg");
	this.shape_9.setTransform(-120.2,11.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgIAfQgGgDgEgEQgFgEgCgHQgDgGAAgHQAAgGADgGQACgHAFgEIAFgEIAFgDQAHgCAGAAIAHABIAGABQAGACAEAEIgGAHQgDgEgEgBIgFgCIgFAAQgFAAgEACQgEACgEADQgDAEgBAEQgCAFAAAEQAAAFACAFQABAFADADQAEAEAEABQAEACAFAAIAIAAIAHgDIAAgRIgOAAIAAgHIAXAAIAAAeIgLAEIgNABQgGAAgHgCg");
	this.shape_10.setTransform(-126.8,11.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.signupmobileleaderboard, new cjs.Rectangle(-132.1,4.3,65.1,14.6), null);


(lib.partyreadyrecipesmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape.setTransform(227.1,-16);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWAmQgEgBAAgDQAAgDAEgCIACgBQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIABgJIAAgFIAAgFIAAgFIgBgSQAAgEgBAAIgEgCQgEgBgBgDIABgDIAGgDIAKgDIAHgBQADAAABAKIAAABIAAAAQAEgGAEgDQAFgDAEAAQAGAAADADQACADAAAGQAAAFgCADQgCADgFAAIgDgBIgDgCIgDgDQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgDAHQgBAIAAAWIAAAKQABAEADAAIADABQAEACAAADQAAADgEABIgOABQgMAAgDgBg");
	this.shape_1.setTransform(220.2,-16);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_2.setTransform(212.6,-16);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcA2QgEgBAAgEQAAgDAFgCIADgCQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBIABgOIAAgDIAAggIgBgTIgJAZQgXA6gEgBQgCABgFgJIgPggIgQgmIgBAeIAAAUIAAAPQAAAAABABQAAABAAAAQAAABAAAAQABAAAAAAIADACQAFACAAADQAAAEgEABIgNABIgMgBQgEgBAAgEQAAgDAEgCQAEgBABgCIACgYIABgqIAAgDIgBgKQAAgBAAAAQAAgBgBgBQAAAAAAAAQgBgBAAAAIgEgCQgFgCAAgCQAAgDAEgCQADgBALAAIALAAIADABQACABAFANIAEALIADAGQASAtABAAQABAAAHgRQAHgPAJgbIACgEQADgJACgCQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAgBIALAAQAKAAADABQAEACAAADQAAADgFABIgCABQgCACgBACQgBADAAAMIABArIACAWQAAACAEABIABAAIADADIABACQAAAEgEABQgEABgNAAIgQgBg");
	this.shape_3.setTransform(201.3,-17.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAPA3IgBgEIAAgDIAAgCIAAAAIgDABIgDADQgFADgEACQgEABgFAAQgNAAgKgKQgIgKgBgRQAAgSALgLQAKgMARAAIAEABIAEACIABAEQAAAEgFAAIgBAAIgCAAQgJAAgFAHQgFAGAAAMQAAAMAFAJQAGAIAJAAQAGAAAFgFQAFgEAAgJIAAgVIAAgiIgBgHQgCgCgDgBIgBgBQgFgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAHgDIAJgDIAHAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAABAAABIAAAEIgBAuIABAgQAAAHABABIAFACQAFABAAACQgBAEgKAEIgIACIgGAAIgDgBg");
	this.shape_4.setTransform(185.6,-17.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAKAmQgDgBAAgDQAAgDADgCIADgBQACAAABgEIAAgLQAAgYgDgGQgDgGgIAAQgDAAgEADQgDACgCAEQgCADgBAGIAAAUIAAAKQAAABABAAQAAABAAAAQAAABABAAQAAAAABAAIACABQAEACAAADQAAADgDABIgOABIgQgBQgDgBAAgDQAAgDADgCIACgBQABAAAAAAQABAAAAgBQAAAAABgBQAAAAAAgBIABgJIAAgFIAAgFIAAgHIgBgRQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAAAgBAAIgEgCQgEgBAAgDQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgDIALgEIAIAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIABAEIAAAFIAAABIABAAIAAAAIACgBIACgCQAIgIAJAAQAFAAAFACQAFADAEAEQADAEACAGQABAGAAAMIAAAJIAAAGIAAADIABAIIADADIABABQAEACAAADQAAADgDABQgEABgMAAIgOgBg");
	this.shape_5.setTransform(176,-16);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgHAQAAIAFABQAAABABAAQAAAAAAABQAAABABAAQAAABAAABQAAADgFAAQgHAAgFAEQgEADAAAHQAAAGAEAEQAEADAGAAQAHABADgEQADgEAAgHIAAgdQAAgGgDgEQgDgDgEAAQgEAAgDABQgDACgDAEIgCACQgFAFgFABQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgDQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_6.setTransform(167.3,-15.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIAXIgBgCIABgCIACgDIAFgIIABgGIAAgBIgDgBQgDgCgDgDQgBgCAAgFQAAgEACgEQAEgDAEAAQAFAAADAFQAEAEgBAHQAAAFgCAEQgBAGgGAIIgCAGIgDACIgFgBg");
	this.shape_7.setTransform(156.7,-11.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgCABIgCAAIgCgCQgCgBgCgHQgCgFgBgGIACgFQAAAAAAAAQABAAAAgBQABAAAAAAQAAAAABAAQAEAAADAGIADAEQACAEAEACQAEABAEAAQAEAAAEgCQADgDAAgEQAAgHgMgFIgEgDQgMgGgFgEQgEgEAAgIQAAgKAHgGQAHgHALAAIAEABIAGABIADgCIADAAQADAAAEAGQAEAGAAAGIgCAFQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgDgBIgFgGQgCgEgDgCQgEgCgDAAQgEAAgDADQgCACAAAEQAAAEADACQACADAIAFIABABQAWAJAAAMQgBALgHAHQgJAHgMAAg");
	this.shape_8.setTransform(150.9,-16);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_9.setTransform(143.4,-16);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglA0QgDgBAAgDQAAgDADgBIAEgCQABgCABgGIABgZIAAgLIgBgbQgBgGgBgBIgEgBQgFgCABgCQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQABgCADgBIALgDIAIgCIADABIABAEIAAAEIAAABIAAABIADgCIADgCQAFgEAEgBQAEgCAEAAQAOAAAJAKQAKALgBAQQAAARgKAMQgKAMgQAAQgGAAgCgCQgCgCAAgDIABgDIADgBIACABIACAAQAIAAAGgHQAFgHAAgLQAAgNgGgIQgFgIgJAAQgHAAgFAEQgEAFAAALIAAAwIABAHIABAFIAEACIADAAIACACIAAACQAAADgEABIgPABIgQgBg");
	this.shape_10.setTransform(134.5,-14.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIABgIIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgCIAMgEIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEACAAACQAAAEgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFAAADACQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_11.setTransform(127.8,-17.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAdQgLgLAAgRQAAgQAMgMQALgMAQAAQANAAAJAHQAIAGAAAJQAAAEgCACQgCACgEAAQgFAAgBgCQgDgBgDgHQgCgFgDgCQgDgCgEAAQgIAAgGAGQgEAHAAALQgBANAIAJQAGAIALAAIAHgBIAGgDIADgCQAEgDACAAIADABIABACIgCAFIgEAFQgGAFgGACQgHADgHAAQgPAAgLgLg");
	this.shape_12.setTransform(121.6,-16);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_13.setTransform(113.4,-16);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAQAmQgHgYgFgFQgEgFgJAAQgFAAAAgEQAAgFAEAAQAMAAAGgFQAHgFgBgKQABgKgHgFQgGgFgLAAIgIAAIgDADIgBAHIAAAPIAAAhIAAAXQABAGABABIAEABQAEACAAADQABADgFACIgQABIgRgBQgDgCAAgDQgBgDAFgCIAEgCQABgBABgJIABggIgBgdQgBgLgBgBIgFgDQgDgCAAgDQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQACgBAFAAIARAAIAPAAIALgBQARAAAIAHQAJAHAAAOQAAAKgFAHQgGAIgLACIAAABQAJABAEAFQAEAFAEANIADAHQADAMAEAAIACAAIADAAIACABIABADQABADgFADQgEACgHAAQgQAAgFgSg");
	this.shape_14.setTransform(104,-17.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgHAXIgCgCIACgCIABgDIAEgIIACgGIAAgBIgDgBQgDgCgDgDQgCgCAAgFQAAgEAEgEQADgDAEAAQAFAAADAFQADAEABAHQAAAFgCAEIgHAOIgEAGIgDACIgDgBg");
	this.shape_15.setTransform(91.8,-11.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgCABIgCAAIgBgCQgDgBgDgHQgBgFAAgGIAAgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQADAAAEAGIADAEQACAEAEACQAEABADAAQAFAAADgCQADgDAAgEQAAgHgLgFIgFgDQgLgGgEgEQgFgEAAgIQAAgKAHgGQAHgHALAAIAFABIAFABIAEgCIACAAQAEAAADAGQADAGABAGIgBAFQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBIgDgGQgEgEgDgCQgCgCgFAAQgDAAgDADQgCACgBAEQAAAEADACQADADAJAFIABABQAUAJAAAMQABALgJAHQgIAHgMAAg");
	this.shape_16.setTransform(86,-16);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AglA0QgDgBAAgDQAAgDADgBIAEgCQABgCABgGIAAgZIAAgLIAAgbQgBgGgBgBIgEgBQgFgCABgCQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQABgCADgBIALgDIAIgCIADABIABAEIAAAEIAAABIAAABIADgCIADgCQAFgEAEgBQAEgCAEAAQAPAAAIAKQAKALgBAQQAAARgKAMQgKAMgQAAQgGAAgCgCQgCgCAAgDIABgDIADgBIACABIACAAQAJAAAFgHQAFgHAAgLQAAgNgGgIQgFgIgJAAQgHAAgFAEQgEAFAAALIAAAwIABAHIABAFIAEACIADAAIACACIAAACQABADgFABIgQABIgPgBg");
	this.shape_17.setTransform(77.9,-14.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIABgIIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgCIAMgEIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEACAAACQAAAEgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFAAADACQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_18.setTransform(71.2,-17.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgPA3QgEgCgBgEQAAgDAFgBIAEgCQABgCABgNIAAgjIAAgUIgBgMIgBgDIgEgBIgEAAQgFABgDABQgDABgCADIgCAFIgDAGIgCACIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgHQAAgKADgGQACgHADABIABAAIAPABIAtAAIAPgBIABAAQADgBACAHQADAGAAAKIgBAHQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgCAAIgCgCIgDgGIgCgFQgCgDgDgBQgDgBgFgBIgEAAIgEABIgBADIgBANIAAATIAAAjQABANABACIAEACQAFABAAADQgBAEgEACIgQAAIgPAAg");
	this.shape_19.setTransform(63.9,-17.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgiAzQgEgEAAgEQAAgEADgDQACgCAEAAIADAAIADACIACACQAAABABABQAAAAABABQAAAAAAAAQABABAAAAQAEAAAEgGQAEgGAAgGQAAgHgFgLIgBgCIgMgaIgHgPQgBgDgFgCIAAAAIgEgCIAAgCQAAgEAEgBQAEgBALgBQALABAEABQADABAAADIAAADIgCABIgCABQgBAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAIABAGIAGAQIAGAOQAAABABABQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIAFgMIAGgPIACgHQAAgDgEgCQgFgDAAgBQAAgBAAgBQABAAAAgBQABAAAAAAQABgBABAAQADgBAJgBQAJABADABQABAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAADgEABIgDABQgEADgFANIgCAGIgKAXQgNAggHAJQgIAKgLAAQgGAAgDgDg");
	this.shape_20.setTransform(50.6,-14.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgHAQAAIAFABQAAABABAAQAAAAAAABQAAABABAAQAAABAAABQAAADgFAAQgHAAgFAEQgEADAAAHQAAAGAEAEQAEADAGAAQAHABADgEQADgEAAgHIAAgdQAAgGgDgEQgDgDgEAAQgEAAgDABQgDACgDAEIgCACQgFAFgFABQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgDQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_21.setTransform(42.6,-15.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAPA3IgBgEIAAgDIAAgCIgBAAIgCABIgDADQgFADgDACQgFABgEAAQgOAAgJgKQgKgKAAgRQAAgSAKgLQALgMAQAAIAFABIADACIACAEQAAAEgFAAIgCAAIgCAAQgIAAgFAHQgFAGAAAMQAAAMAGAJQAFAIAIAAQAIAAAEgFQAFgEgBgJIAAgVIAAgiIgBgHQAAgBAAAAQgBgBAAAAQAAAAgBgBQgBAAAAAAIgDgBQgEgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAIgDIAJgDIAHAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAABAAABIgBAEIAAAuIAAAgQABAHABABIAFACQAEABAAACQAAAEgLAEIgHACIgGAAIgDgBg");
	this.shape_22.setTransform(34,-17.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAgBIABgIIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgCIAMgEIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEACAAACQAAAEgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFAAADACQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_23.setTransform(26.8,-17.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMA3QgEgBAAgDQAAgDADgCIAEgCQACgBAAgEIABgPIAAgMIgBgOIAAgGIAAgYQgBgGgBgBIgFgBQgFgCAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAGgEIALgDIAHgBQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAGIAAAFIgBA3IAAAZIACAHIAEACQAEACAAADQAAADgEABIgOABIgOgBg");
	this.shape_24.setTransform(22.2,-17.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_25.setTransform(15.7,-16);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AARA2QgEgBAAgEQAAgDAEgCIAEgCQABgBABgEIAAgSIAAgLIgBgDQAAAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQgEgBgOAAIgQAAIgFACIgBACIAAAGIAAAGIAAASQABAEABABIADACQAFACAAADQAAAEgEABIgQABIgRgBQgEgBAAgEQAAgDAFgCIADgCQACgBABgJIAAggIAAgdIgCgMIgFgDQgEgBAAgDQAAgDAEgCQADgBAOAAQANAAAEABQADACAAADQAAACgFACIgDACQgBABgBAEIAAAXQAAADACABQADABALAAIAGAAIAQAAIAGgCIABgBIAAgDIAAgEIAAgSQgBgEgBgBIgEgCQgEgCAAgCQAAgDADgCQAEgBANAAQAOAAADABQAEACAAADQAAACgFACIgEACQgBABgBALIgBAeIABAdQABALABACIAFACQAEACAAADQAAAEgFABIgQABQgMAAgEgBg");
	this.shape_26.setTransform(5.5,-17.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipesmobileleaderboard, new cjs.Rectangle(-2.4,-28.8,235.9,22.2), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalebackground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D6E47").s().p("A6bFUIAAqnMA04AAAIAAKng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalebackground, new cjs.Rectangle(-169.2,-34,338.5,68), null);


(lib.getinspiredrollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("Al9BcIAAi3IL8AAIAAC3g");
	this.shape.setTransform(0,0,1.07,0.903);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.getinspiredrollovervideo, new cjs.Rectangle(-40.9,-8.3,81.9,16.7), null);


(lib.fillinboxmobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgCABIgCAAIgCgCQgCgBgCgHQgCgGAAgFIABgFQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAEAAADAGIADAEQACAEAEABQAEACAEAAQAEAAAEgCQADgDAAgEQAAgHgMgFIgFgDQgLgFgFgFQgEgEAAgIQAAgKAHgGQAHgHALAAIAEABIAGABIADgCIADAAQAEAAADAGQAEAGAAAGIgBAFQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgDgBIgFgGQgCgEgDgCQgEgCgDAAQgEAAgDADQgDACABAEQAAAEACACQADADAIAFIACAAQAUAKABAMQAAALgJAHQgIAHgMAAg");
	this.shape.setTransform(169.9,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_1.setTransform(162.6,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgJIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgDIAMgDIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEABAAAEQAAADgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFgBADADQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_2.setTransform(156.4,-0.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWAmQgEgCAAgDQAAgCAEgBIABgCQABAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIABgJIAAgEIAAgGIAAgFIgBgSQAAgEgCAAIgDgCQgEgBgBgDIABgDIAGgDIAKgDIAHgCQADAAABALIAAABIAAAAQAEgFAEgEQAFgDAEAAQAFAAADADQADAEABAFQgBAFgCADQgCADgEAAIgFgBIgCgCIgCgDQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgFAAgCAHQgCAIAAAWIAAAKQACAEACAAIACACQAFABAAADQAAADgEABIgOABQgLAAgEgBg");
	this.shape_3.setTransform(151.6,0.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_4.setTransform(144.2,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAiAmQgEgBAAgDQAAgDAEgBIACgCQACgBACgDIAAgOQAAgVgDgGQgDgGgIAAQgJAAgDAHQgFAJAAARIAAAEIABALQAAABABAAQAAABAAAAQABABAAAAQAAAAABAAIACACQAEABgBACQABADgEACQgDABgMAAQgKAAgDgBQgEgBAAgDQAAgDAEgBIADgCQAAAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIAAgLQAAgYgCgGQgEgGgHAAQgEAAgEADQgEACgCAEIgCAKIgBATIABAKIACADIADACQADABABADQgBADgDABIgOABQgLAAgEgBQgEgCAAgDQAAgCAEgBIACgCQAAAAABAAQAAAAABgBQAAAAAAgBQAAAAABgBIABgJIAAgEIgBgGIAAgFIAAgSQgBgEgBAAIgEgCQgFgBABgDIABgDIAEgCIAMgFIAHgBQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABABAAABIAAADIAAABIAAABIAAAAIAAAAIACgCIABAAQAJgJAKAAIAGABQAEABADACQACACADADIAEAEIACgCIAEgDQAEgFAFgCQADgBAEAAQAJAAAHADQAGAEADAGQAEAIAAAVIAAAIIAAAEIAAADIABAGQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAIABACQAFABAAACQAAADgFACQgDABgLAAIgPgBg");
	this.shape_5.setTransform(132.9,0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_6.setTransform(121.9,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAcA2QgEgBAAgEQAAgDAFgCIADgCQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIABgOIAAgDIAAggIgBgTIgJAZQgXA6gEgBQgCAAgFgIIgPggIgQglIgBAdIAAAUIAAAPQAAAAABABQAAABAAAAQAAABAAAAQABAAAAAAIADACQAFACAAADQAAAEgEABIgNABIgMgBQgEgBAAgEQAAgCAEgDQAEgBABgCIACgYIABgqIAAgDIgBgKQAAgBAAAAQAAgBgBgBQAAAAAAAAQgBgBAAAAIgEgBQgFgDAAgDQAAgCAEgBQADgCALAAIALAAIADABQACABAFANIAEALIADAGQASAtABAAQABAAAHgRQAHgPAJgbIACgEQADgJACgCQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAgBIALAAQAKAAADACQAEABAAACQAAADgFACIgCABQgCABgBADQgBADAAAMIABArIACAWQAAABAAAAQABAAAAABQABAAAAAAQABABABAAIABAAIADADIABACQAAAEgEABQgEABgNAAIgQgBg");
	this.shape_7.setTransform(111,-0.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFAnIgIgBIgCABIgDABIgBAAIgCgCQgCgBgDgHQgCgGAAgFIABgFQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABAAQADAAAEAGIADAEQACAEAEABQAEACADAAQAGAAACgCQAEgDAAgEQAAgHgMgFIgEgDQgNgFgEgFQgEgEAAgIQAAgKAHgGQAHgHALAAIAFABIAFABIAEgCIACAAQADAAAEAGQAEAGgBAGIgBAFQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEgBIgEgGQgCgEgEgCQgDgCgDAAQgEAAgDADQgDACAAAEQABAEADACQACADAIAFIABAAQAWAKAAAMQgBALgHAHQgJAHgMAAg");
	this.shape_8.setTransform(96.7,0.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AARAnIgBgEIAAgFIgBgBIgDACIgBABQgDAEgFACQgDACgGAAQgGAAgFgCQgFgDgDgEQgEgEgBgGQgCgHAAgPIAAgFIAAgGIAAgBQAAgGgBgCQAAgBAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgDgBQgFgBAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIAHgDIAKgDIAIgBQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABAGIAAACIgBAdQAAAOAEAHQADAFAHAAQAIAAAEgHQAEgIAAgSIAAgFIgBgIQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgEgBQgEgBAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIAHgDIAKgDIAIgBQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAGIAAAEIgBAfIAAAMIAAAFQABADAEACIABAAQAFACAAADIgCACIgEADIgLAEIgIABQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAg");
	this.shape_9.setTransform(88.8,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgbAdQgLgMAAgRQAAgQAMgLQALgMAQAAQARAAAKALQALALAAAQQAAARgLAMQgMAMgQAAQgQAAgLgLgAgOgWQgEAGAAALQAAAOAGAKQAHAKAIAAQAHAAAFgGQAFgGAAgLQAAgOgHgKQgGgKgIAAQgIAAgFAGg");
	this.shape_10.setTransform(80.1,0.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgJIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgDIAMgDIAHgCQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEABAAAEQAAADgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFgBADADQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_11.setTransform(73.6,-0.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAdQgLgLAAgRQAAgQAMgMQALgMAQAAQAMAAAJAHQAJAGAAAJQAAAEgCACQgDACgEAAQgDAAgDgCQgCgBgCgHQgDgFgDgCQgDgCgFAAQgHAAgFAGQgFAHgBALQABANAGAJQAIAIAJAAIAIgBIAGgDIADgCQAEgDADAAIACABIABACIgBAFIgFAFQgGAFgGACQgHADgIAAQgOAAgLgLg");
	this.shape_12.setTransform(67.7,0.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgNA3QgDgCAAgDQAAgCADgCIACgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgJIAAgFIAAgGIAAgIIgBgPQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgCQgEgBAAgCQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAFgDIAMgDIAHgCQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABAFIAAAFIgBADIAAASIAAABIAAASIAAALQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIACABQAEABAAAEQAAADgDABIgOAAIgPAAgAgIglQgEgDAAgEQAAgFAEgDQADgCAFAAQAFgBADADQADADAAAEQAAAEgDADQgEADgEAAQgFAAgDgCg");
	this.shape_13.setTransform(61.5,-0.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgMA3QgEgCAAgDQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAAAIAEgDQACgBAAgEIABgPIAAgMIgBgOIAAgGIAAgYQgBgGgBgBIgFgBQgFgCAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAGgDIALgDIAHgBQAAAAABAAQAAAAABAAQAAABAAAAQAAAAABAAIABAGIAAAGIgBA2IAAAaIACAGIAEADQAEABAAADQAAADgEABIgOABIgOgBg");
	this.shape_14.setTransform(57.2,-1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_15.setTransform(51.1,0.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQA3IgJAAIgGAAIgHAAQgJAAgDgBQgDgBAAgEQAAgDAEgBIAEgDQACgBAAgMIABgdIgBgcQgBgLgBgCIgEgDQgEgBAAgDQAAgDADgCIAMgBIAHAAIAIAAIAKAAIAJAAQAbAAAQAPQAPAOAAAaQAAAbgQAOQgQANgdAAgAgQgqQgEABAAACQgCADAAAJIAAAXIAAAcIACAPQAAACAGACQAEABAIAAQAQAAAJgKQAJgLAAgVQAAgWgKgMQgLgMgSAAQgGAAgDACg");
	this.shape_16.setTransform(41.2,-0.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYAdQgLgLAAgRQAAgRALgLQAMgMAQAAQAPAAAIAJQAJAIAAAOQAAAFgBACQgCABgGAAIgcAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAEgBIAPAAIAEAAIABgCQAAgIgFgFQgFgFgHAAQgIAAgFAIQgEAIAAALQAAALAGAJQAGAIAJAAIAJgBIAIgEIADgCQADgDADAAIACABIABADIgBAEIgGAGQgGAFgGADQgHACgHAAQgPAAgLgLg");
	this.shape_17.setTransform(27.2,0.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAZA4IgEAAQgDgCgHgJIgDgEIgBgCQgTgYgBAAIgBABIgBADIAAAEIABAQIABAFIAFADQAEABgBADQABADgEABIgOABIgPgBQgEgCAAgDQAAgCAEgBIACgCQABAAABgEIABgNIAAgKIAAgLIAAgJIAAgcQAAgHgCgCIgEgBIgDgBIgCgBIgBgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAHgDIALgDIAIgBQAAAAAAAAQABAAAAAAQABABAAAAQAAAAAAAAIABAGIAAAPIgBATIAAATIABADIABABIAEgCIAFgEIAGgHIACgDQAAAAAAgBQAAAAAAAAQgBAAAAgBQgBAAAAgBQgBAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgDAEgCQADgBAMgBQAGABAEABQAEACgBADQABADgGABIgIADIgJAIIgBABIgDACIgBACQAAABAHAJIABABIANAQIAIAIIAHADQAFACAAADQAAAEgEABIgMABg");
	this.shape_18.setTransform(19.2,-1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAOAkIgEgEIgEABQgIAHgKAAQgLAAgHgHQgHgGAAgLQAAgMAJgGQAJgGAQgBIAFABQAAABABAAQAAABAAAAQABABAAAAQAAABAAABQAAADgFAAQgHAAgFAEQgEAEAAAGQAAAGAEADQAEAEAGAAQAHAAADgDQADgEAAgHIAAgcQAAgHgDgEQgDgEgEAAQgEAAgDACQgDACgDAEIgCABQgFAGgFABQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgBAAgEQAAgHAJgFQAIgFAOAAQAIAAAGACQAGACADAFQADADABAFIABAPIAAAXIAAAHIADACIACABQAFABAAADQAAAEgFADQgGADgGAAQgEAAgDgEg");
	this.shape_19.setTransform(10.7,0.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAcA2QgEgBAAgEQAAgDAFgCIADgCQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIABgOIAAgDIAAggIgBgTIgJAZQgXA6gEgBQgCAAgFgIIgPggIgQglIgBAdIAAAUIAAAPQAAAAABABQAAABAAAAQAAABAAAAQAAAAABAAIADACQAFACAAADQAAAEgEABIgNABIgMgBQgEgBAAgEQAAgCAEgDQAEgBABgCIACgYIABgqIAAgDIgBgKQAAgBAAAAQAAgBgBgBQAAAAAAAAQgBgBAAAAIgEgBQgFgDAAgDQAAgCAEgBQADgCALAAIALAAIADABQACABAFANIAEALIADAGQASAtABAAQABAAAHgRQAHgPAJgbIACgEQADgJACgCQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABgBIALAAQAKAAADACQAEABAAACQAAADgFACIgCABQgCABgBADQgBADAAAMIABArIACAWQAAABAAAAQABAAAAABQABAAAAAAQABABABAAIABAAIADADIABACQAAAEgEABQgEABgNAAIgQgBg");
	this.shape_20.setTransform(-0.4,-0.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.fillinboxmobileleaderboard, new cjs.Rectangle(-11.1,-12,188,22.2), null);


(lib.ctamobileleaderboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AoEBjIAAjFIQIAAIAADFg");
	this.shape.setTransform(8.3,1.8,0.454,0.662);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctamobileleaderboard, new cjs.Rectangle(-15.1,-4.7,46.9,13.1), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.mobileleaderboardgetinspired_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(2));

	// Layer 1
	this.instance = new lib.getinspiredrollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.9,-8.3,81.9,16.7);


// stage content:
(lib.mobileleaderboardgetinspired = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_28 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_168 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(28).call(this.frame_28).wait(140).call(this.frame_168).wait(3));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,25.5,1.558,0.078,0,0,0,0.2,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(171));

	// fade-from-white
	this.instance = new lib.blackwideskyscraper();
	this.instance.parent = this;
	this.instance.setTransform(161,25.5,1.954,0.085,0,0,0,0.3,0);
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.1,scaleX:1.95,scaleY:0.08,x:160.1,y:25,alpha:0},9).wait(162));

	// white-logo
	this.instance_1 = new lib.whitelogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(281.9,23.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({scaleX:0.02,scaleY:0.02,x:40},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(149));

	// make-delicious-mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AsTClIAAkcMAlFAAAIAAEcg");
	mask.setTransform(158.6,16.5);

	// make-delicious-memories
	this.instance_2 = new lib.fillinboxmobileleaderboard();
	this.instance_2.parent = this;
	this.instance_2.setTransform(76.4,14.6);
	this.instance_2.alpha = 0;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(16).to({x:-94.5,y:15.6},0).to({x:88.4,y:14.6,alpha:1},10,cjs.Ease.get(1)).to({x:86.4},6,cjs.Ease.get(1)).wait(44).to({alpha:0},5).wait(90));

	// holiday-mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AtAClIAAkcMAmAAAAIAAEcg");
	mask_1.setTransform(160,16.5);

	// holiday tips, recipes, more
	this.instance_3 = new lib.partyreadyrecipesmobileleaderboard();
	this.instance_3.parent = this;
	this.instance_3.setTransform(79.2,31.4);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(76).to({x:-117.8,y:32.8},0).to({x:81.2,y:31.4,alpha:1},10,cjs.Ease.get(1)).to({x:79.2},6,cjs.Ease.get(1)).wait(79));

	// sign-up-mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AlwD6IAAkcIZKAAIAAEcg");
	mask_2.setTransform(124.2,25);

	// sign-up
	this.cta_rollover = new lib.signupmobileleaderboard();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(207.6,24.3);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(28).to({x:133.9,y:22.6},0).to({x:224.5,y:23.3,alpha:1},10,cjs.Ease.get(1)).to({x:219.5},8,cjs.Ease.get(1)).wait(125));

	// rollover-mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("ApvDrIAAmoIf1AAIAAGog");
	mask_3.setTransform(141.4,23.5);

	// rollover
	this.cta_rollover_1 = new lib.mobileleaderboardgetinspired_1();
	this.cta_rollover_1.parent = this;
	this.cta_rollover_1.setTransform(125,36.2);
	this.cta_rollover_1.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover_1).wait(28).to({x:35.8,y:35.2},0).to({x:125,alpha:1},10,cjs.Ease.get(1)).to({x:120},8).wait(125));

	// cta-mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("ApvDrIAAmoIf1AAIAAGog");
	mask_4.setTransform(141.4,23.5);

	// cta-rectangle
	this.instance_4 = new lib.ctamobileleaderboard();
	this.instance_4.parent = this;
	this.instance_4.setTransform(105.5,33.9,1.745,1.269);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(28).to({x:21.3,y:32.9},0).to({x:110.5,alpha:1},10,cjs.Ease.get(1)).to({x:105.5},8,cjs.Ease.get(1)).wait(125));

	// kale-background
	this.instance_5 = new lib.kalebackground();
	this.instance_5.parent = this;
	this.instance_5.setTransform(162.3,28.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(171));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(153.1,19.1,338.5,68);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;